/* Generated By:JavaCC: Do not edit this line. CompiladorClasesConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorClasesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tCLASE = 5;
  /** RegularExpression Id. */
  int tMETODO = 6;
  /** RegularExpression Id. */
  int tENTERO = 7;
  /** RegularExpression Id. */
  int tDECIMAL = 8;
  /** RegularExpression Id. */
  int tLLAVE_IZQ = 9;
  /** RegularExpression Id. */
  int tLLAVE_DCHA = 10;
  /** RegularExpression Id. */
  int DIGITO = 11;
  /** RegularExpression Id. */
  int LETRA = 12;
  /** RegularExpression Id. */
  int tVALOR_ENTERO = 13;
  /** RegularExpression Id. */
  int tVALOR_DECIMAL = 14;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 15;
  /** RegularExpression Id. */
  int tASIGNACION = 16;
  /** RegularExpression Id. */
  int tFIN_SENTENCIA = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"clase\"",
    "\"metodo\"",
    "\"entero\"",
    "\"decimal\"",
    "\"{\"",
    "\"}\"",
    "<DIGITO>",
    "<LETRA>",
    "<tVALOR_ENTERO>",
    "<tVALOR_DECIMAL>",
    "<tIDENTIFICADOR>",
    "\"=\"",
    "\";\"",
  };

}
